/*
 * WARNING: This is a generated file. Do not modify directly.
 * Any changes made to this file will be overwritten.
 * 
 * Generated on: 2024-07-05
 * Generated by: TELEports tlparser.py
 * 
 * For any modifications, please edit the source templates and regenerate this file.
 */
    
#include "qx_td_message_chat_set_message_auto_delete_time.h"

#include "utils/qx_td_translate_tools.h"

QxTdMessageChatSetMessageAutoDeleteTime::QxTdMessageChatSetMessageAutoDeleteTime(QObject *parent)
    : QxTdMessageContent(parent)
{
    setType(MESSAGE_CHAT_SET_MESSAGE_AUTO_DELETE_TIME);
}

QxTdMessageChatSetMessageAutoDeleteTime::QxTdMessageChatSetMessageAutoDeleteTime(QObject *parent, qint32 messageAutoDeleteTime_, qint64 fromUserId_)
    : m_messageAutoDeleteTime(messageAutoDeleteTime_)
    , m_fromUserId(fromUserId_) {
}

qint32 QxTdMessageChatSetMessageAutoDeleteTime::messageAutoDeleteTime() const {
    return m_messageAutoDeleteTime;
}

void QxTdMessageChatSetMessageAutoDeleteTime::setMessageAutoDeleteTime(qint32 value) {
    if (m_messageAutoDeleteTime != value) {
        m_messageAutoDeleteTime = value;
        emit dataChanged();
    }
}

qint64 QxTdMessageChatSetMessageAutoDeleteTime::fromUserId() const {
    return m_fromUserId;
}

void QxTdMessageChatSetMessageAutoDeleteTime::setFromUserId(qint64 value) {
    if (m_fromUserId != value) {
        m_fromUserId = value;
        emit dataChanged();
    }
}

QJsonObject QxTdMessageChatSetMessageAutoDeleteTime::marshalJson() {
    return QJsonObject{
        { "@type", QxTdObject::typeString() },
        { "message_auto_delete_time", m_messageAutoDeleteTime },
        { "from_user_id", m_fromUserId }
    };
}

void QxTdMessageChatSetMessageAutoDeleteTime::unmarshalJson(const QJsonObject &json) {
    QJsonObject jsonObj;
    QJsonArray jsonArray;

    QxTdMessageContent::unmarshalJson(json);
    m_messageAutoDeleteTime = json["message_auto_delete_time"].toInt();
    m_fromUserId = json["from_user_id"].toVariant().toLongLong();
    
    m_typeText = qxTranslate("Self-destruct timer was set");
    emit dataChanged();
}
